apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka 
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka
        ports:
        - containerPort: 19092
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"

        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        # - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
        #   value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_CFG_LISTENERS
          value: CLIENT://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
        - name: KAFKA_CFG_LISTENER.SECURITU.PROTOCOL.MAP
          value: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        # - name: KAFKA_CFG_ADVERTISED_LISTENERS
        #   value: CLIENT://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092  
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "CLIENT"

        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"

      - name: kafka-exporter
        image: bitnami/kafka-exporter
        # command: ["sh", "-c", "sleep 100000"]
        command: ["kafka_exporter", "--kafka.server=127.0.0.1:9092"]
        ports:
        - containerPort: 9308
        # args: ["--kafka.server=127.0.0.1:9092"]
        # args:
        #   - "--kafka.server=127.0.0.1:9092"
          # --kafka.server=kafka:9092
        
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
    # protocol: TCP
    name: kafka-external
  - port: 19092
    targetPort: 19092
    name: kafka-client
    
  - port: 9308
    targetPort: 9308
    name: kafka-exporter

  selector:
    app: kafka
  clusterIP: None



        # - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
        #   value: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
          # value: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        # - name: KAFKA_CFG_LISTENERS
        #   value: "CLIENT://:19092,EXTERNAL://:9092"
        # - name: KAFKA_CFG_LISTENERS
        #   value: "CLIENT://:9092"
        # - name: KAFKA_INTER_BROKER_LISTENER_NAME
        #   value: "CLIENT"
        
        # - name: KAFKA_ADVERTISED_PORT
        #   value: "9092"
        # - name: KAFKA_ADVERTISED_HOST_NAME
        #   value: "load-balancer URL"
        # - name: KAFKA_ZOOKEEPER_CONNECT
        #   value: zoo1:2181
        # - name: KAFKA_CREATE_TOPICS
        #   value: "test-topic:3:2:compact"
        # - name: KAFKA_LOG_DIRS
        #   value: /kafka/kafka-logs
        # - name: KAFKA_BROKER_ID
        #   value: "1"
        # - name: KAFKA_JMX_PORT
        #   value: "5555"
        # - name: KAFKA_CLEANUP_POLICY
        #   value: "compact"
        

      #   volumeMounts:
      #     - name: xr-volume
      #       mountPath: "/kafka/kafka-logs"
      # volumes:
      #     - name: xr-volume
      #       nfs:
      #         server: xxxxx.efs.eu-west-1.amazonaws.com
      #         path: /kafka-k8/logs/broker1