apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
  labels:
    name: prometheus-cm
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s    # How frequently to scrape targets by default.
      scrape_timeout: 10s     # How long until a scrape request times out.

    scrape_configs:
      - job_name: kafka
        # scrape_timeout: 90
        static_configs:
          - targets: ['kafka:9898']

      # - job_name: 'node-exporter'
      #   kubernetes_sd_configs:
      #     - role: endpoints
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_endpoints_name]
      #     regex: 'node-exporter'
      #     action: keep
    



